version: "3.8"

services:
  frontend:
    build:
      # context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: api-network